version: '3.8'

services:
  # Application
  app:
    image: php:8.3-fpm
    container_name: rptra_proker_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - rptra

  # Webserver
  webserver:
    image: nginx:alpine
    container_name: rptra_proker_web
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8000:80"
    networks:
      - rptra

  # Database
  db:
    image: mysql:8.4
    container_name: rptra_proker_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - rptra

networks:
  rptra:

volumes:
  dbdata: